spring.application.name=mscuadrilla
server.port=8087

spring.datasource.url=jdbc:h2:file:./mscuadrilla/data/cuadrilla_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=dev

springdoc.api-docs.path=/api/cuadrilla/v3/api-docs