services:
  ms-especies:
    build: ./msespecies
    container_name: ms-especies
    ports:
      - "8082:8082"
    environment:
      MS_ESPECIES_URI: http://ms-especies:8082
    volumes:
      - ./msespecies/data:/app/data

  mspredios:
    build: ./mspredios
    container_name: mspredios
    ports:
      - "8080:8080"
    environment:
      MS_PREDIOS_URI: http://mspredios:8080
    volumes:
      - ./mspredios/data:/app/data

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      MS_PREDIOS_URI: http://mspredios:8080
      MS_ESPECIES_URI: http://ms-especies:8082
    depends_on:
      - mspredios
      - ms-especies