spring.application.name=mspredios
server.port=8080

# 1. URL corregida (debe estar asignada a la propiedad)
spring.datasource.url=jdbc:h2:mem:prediosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Hibernate en 'none' o 'validate' es correcto para Flyway
spring.jpa.hibernate.ddl-auto=none

# 3. Consola H2
spring.h2.console.enabled=true

# 4. (Opcional) Asegura que Flyway limpie la BD si hay errores (solo para desarrollo)
spring.flyway.clean-disabled=false
