spring.application.name=mspredios
server.port=8080
spring.datasource.url=jdbc:h2:mem:prediosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
spring.flyway.clean-disabled=false