spring.application.name=cliente
server.port=8081

spring.datasource.url=jdbc:h2:file:./mscliente/data/cliente_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Rutas personalizadas para Swagger UI y la documentación JSON
springdoc.swagger-ui.path=/doc/swagger-ui.html
spring.profiles.active=dev
springdoc.swagger-ui.enable=true


