spring.application.name=despachoo
server.port=8083
spring.datasource.url=jdbc:h2:file:./data/despachoodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api/despacho/v3/api-docs
server.forward-headers-strategy=framework