CREATE TABLE predios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    ciudad VARCHAR(100) NOT NULL,
    comuna VARCHAR(100) NOT NULL,
    dueno VARCHAR(100) NOT NULL
);

INSERT INTO predios (nombre, ciudad,comuna, dueno)
VALUES ('Predio Las Quemas','Osorno', 'Osorno', 'Ernesto Mitt');
INSERT INTO predios (nombre, ciudad,comuna, dueno)
VALUES ('Cancha de acopio Rio Bueno','Rio Bueno', 'Rio Bueno','AAA');
INSERT INTO predios (nombre, ciudad,comuna, dueno)
VALUES ('Predio Las Quemas','Las Quemas', 'Osorno', 'Ernesto Mitt');