CREATE TABLE predios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    ubicacion VARCHAR(100) NOT NULL,
    dueno VARCHAR(100) NOT NULL
);

INSERT INTO predios (nombre, ubicacion, dueno)
VALUES ('Predio Las Quemas', 'Osorno', 'Ernesto Mitt');