server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: especies-routes
          uri: ${MS_ESPECIES_URI:http://localhost:8082}
          predicates:
            - Path=/api/especies/**
        - id: predios-routes
          uri: ${MS_PREDIOS_URI:http://localhost:8080}
          predicates:
            - Path=/api/predios/**
        - id: factura-routes
          uri: ${MS_FACTURA_URI:http://localhost:8084}
          predicates:
            - Path=/api/factura/**
        - id: planCosecha-routes
          uri: ${MS_PLANCOSECHA_URI:http://localhost:8089}
          predicates:
            - Path=/api/planCosecha/**

        # Rutea /api/cliente/** al ms-cliente (puerto 8081)
        - id: cliente-routes
          uri: ${MS_CLIENTE_URI:http://localhost:8081}
          predicates:
            - Path=/api/cliente/**

        # Rutea /api/v1/cuadrillas/** al ms-cuadrilla (puerto 8088)
        - id: cuadrilla-routes
          uri: ${MS_CUADRILLA_URI:http://localhost:8088}
          predicates:
            - Path=/api/v1/cuadrillas/**

        # Rutea /api/v1/epps/** y /api/v1/accidentes/** al ms-seguridad (puerto 8085)
        - id: seguridad-routes
          uri: ${MS_SEGURIDAD_URI:http://localhost:8085}
          predicates:
            - Path=/api/v1/epps/**,/api/v1/accidentes/**