spring.application.name=msespecies
server.port=8082
spring.datasource.url=jdbc:h2:mem:especiesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Ya que no se utiliza Flyway esta propiedad debe estar en "create" o "update"
# de lo contrario no se creara la base de datos
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true