spring.application.name=msespecies
server.port=8082
# Al ejecutar la app en Intellij se debe hacer abriendo la carpeta raiz del proyecto
# de otro modo se creara un data que no corresponde,y se guardaran de forma erronea los datos
spring.datasource.url=jdbc:h2:file:./data/especiesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.profiles.active=dev
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enable=true
springdoc.swagger-ui.path=/doc/swagger-ui.html