spring.application.name=msacopio
server.port=8087
# Base de datos H2
spring.datasource.url=jdbc:h2:file:./data/msacopio_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enable=true
springdoc.swagger-ui.path=/doc/swagger-ui.html