spring.application.name=msplanCosecha
# Puerto del microservicio
server.port=8089

# Datasource creara un archivo donde almacenaran los datos
# en este caso creara una carpeta llamada data, y un archivo llamado planCosechadb
spring.datasource.url=jdbc:h2:file:./data/planCosechadb
# Prepara la metodologia de comunicacion con H2
spring.datasource.driverClassName=org.h2.Driver
# Da acceso al System Administrator para usar la consola de H2
# y conectar con la app
spring.datasource.username=sa
spring.datasource.password=

# Para que JPA pueda interactuar con H2
# dejamos este atributo en update
# Actualizara los objetos ya presentes en caso de que cambie la estructura
spring.jpa.hibernate.ddl-auto=update

# Se deja activa la consola de H2 para inspeccion directa de datos
spring.h2.console.enabled=true

spring.profiles.active=dev

# Permite la documentacion
springdoc.api-docs.enabled=true

# Estos dos atributos permiten que Swagger se active
# y tenga una direccion URL valida
# Activar Swagger no impide las consultas directas
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# URL del microservicio de Plan de Cosecha con valor por defecto
ms.plancosecha.url=${MS_PLANCOSECHA_URL:http://localhost:8089}
