spring.application.name=msfactura
# Puerto del microservicio
server.port=8084

# Datasource creara un archivo donde se almacenaran los datos
# En este caso creara una carpeta llamada data, y un archivo llamado facturadb
spring.datasource.url=jdbc:h2:file:./data/facturadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Para que JPA pueda interactuar con H2
# Actualizara los objetos ya presentes en caso de que cambie la estructura de las entidades
spring.jpa.hibernate.ddl-auto=update

# Se deja activa la consola de H2 para inspección directa de datos
spring.h2.console.enabled=true

spring.profiles.active=dev

# Configuración de Swagger/OpenAPI
# Permite la documentación y define su ruta de acceso
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

# URL del microservicio de facturación con valor por defecto
ms.factura.url=${MS_FACTURA_URI:http://localhost:8089}