spring.application.name=msfactura
server.port=8084
spring.datasource.url=jdbc:h2:file:./data/facturadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.profiles.active=dev
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enable=true
ms.factura.url=${MS_FACTURA_URL:http://localhost:8084}
springdoc.api-docs.path=/api/factura/v3/api-docs